fundapps/TechDocs

- README.md
Relates to the changes in fundapps/rapptr#1477
> Updated the section on /v1/expost/result

- Sample-ImportFiles/README.md
To be sent to Stavroula (AAM) in response to zd(3320).
> Create README explaining transaction file format

- README.md
Can be reviewed here: https://github.com/mgkeen/api-examples/tree/transactionsMethod
> Added transaction import to readme

- Sample-ImportFiles/Issuer Register.csv
- Sample-ImportFiles/README.md
Connected to https://github.com/fundapps/Rapptr/issues/4678
Merge once other PR has been deployed
> Switch import for issuer register from "Name" to "LegalName"

- Sample-XML/Position Limits.xml
@Ben-Richards or @Patrick-Willis do you mind taking a quick look please?
> Position limits sample file

- Ruby/fundapps-api.rb
Ruby needs this hash key quoted.
> Fix passing of content name header

- Node/example.js
Added a little example based on what I through together for feature testing.
> Node example

- Sample-ImportFiles/Issuer Register.csv
added LEI column and values for issuers
> adding LEI to sample import

- Sample-XML/Rights xml
Update to API examples to include rights
> Create Rights xml

- Curl/example.sh
we should not be saying it is possible to upload CSV position files, so changing to positions.xml
https://fundapps.slack.com/archives/C1T1DAJLS/p1561002752330900?thread_ts=1560956740.300400&cid=C1T1DAJLS
> Update example.sh script

- README.md
Add max file size info
100MB calculated from this: https://github.com/fundapps/Rapptr/blob/9e256dcb3e920bdcd10aa68ac324b6b6b1bd1758/src/FundApps.Rapptr.Api/Web.config#L64
https://fundapps.slack.com/archives/C1T1DAJLS/p1561021488336700?thread_ts=1560956740.300400&cid=C1T1DAJLS
> Add max file size info

- Sample-ImportFiles/README.md
> update page to include (case sensitive) for Buy Sell transaction type

- C#/dotnet-core-example.cs
- C#/example.cs
Small example demonstrating uploading positions file via api in .Net core project.
> Add example for uploading using HttpClient in .Net core

- Java/build.gradle
- Java/src/main/java/co/fundapps/examples/UploadPositionFile.java
simple code to make HTTP POST request to API. Production users will want to think more carefully about error handling and secret management.
> Java API example 

- Sample-XML/Multiple Asset Classes.xml
> Fixing broken xml sample file

- Sample-XML/Structured Product.xml
Updating the Structured Product XML example to include the new 'WeightingQuantity' property. 
Probably want to wait till the PR is deployed
> Update SP to include WQ property

- Sample-XML/Desk Level Assets.xml
Adding in Desk Level Assets XML
> Desk Level Assets

- PowerShell/DownloadDisclosures/DownloadDisclosures.ps1
> url to export data has changed

- README.md
https://www.notion.so/fundapps/File-Upload-Limits-c6bc179f75e343788e8e62ad13122497
> update API file max file size

- README.md
( waiting on https://github.com/fundapps/Rapptr/pull )
> Add user provision api

- Adapptr/Position Limits/PositionLimits_Adapptr.csv
As per https://docs.fundapps.co/PropertiesAdapptrPL.html
> Adding fields to PL Adapptr example file

- Sample-XML/Desk Level Assets.xml
Correct attribute name is Date rather than DataDate
> Fix snapshot XML date attribute

- .gitignore
- Adapptr/Sample-Code&Scripts/Powershell/check-task-status.ps1
- Adapptr/Sample-Code&Scripts/Powershell/entry-provider-credentials.ps1
- Adapptr/Sample-Code&Scripts/Powershell/post-data-provider-credentials.ps1
- Adapptr/Sample-Code&Scripts/Powershell/upload-positions-without-enrichment.ps1
- Adapptr/Sample-Code&Scripts/Powershell/upload-positions.ps1
- Adapptr/versions/v2.md
Added a power shell script to provide for the user a data entry command line to entry the data necessary for data provider registration.
The script obscure the password.
Also added a new section at the documentation that mention each power shell script and its main function.
> Added extra script to provide a data entry for data provider credentials registration

- Adapptr/Sample-Code&Scripts/Powershell/entry-provider-credentials.ps1
Extra `ent` made it into the script erroneously
> Update some small typos in the data entry script

- README.md
Updated the Portfolio import docs to reflect the recent changes to the output.
I have included sample responses based on different scenarios.
> Add example portfolio import api responses

- Adapptr/Sample-Code&Scripts/C#/DataProviderCredentials.cs
- Adapptr/Sample-Code&Scripts/C#/TaskStatus.cs
- Adapptr/Sample-Code&Scripts/C#/UploadPositions.cs
- Adapptr/Sample-Code&Scripts/C#/UploadPositionsWithoutEnrichment.cs
- Adapptr/Sample-Code&Scripts/Powershell/check-task-status.ps1
- Adapptr/Sample-Code&Scripts/Powershell/post-data-provider-credentials.ps1
- Adapptr/Sample-Code&Scripts/Powershell/upload-positions-without-enrichment.ps1
- Adapptr/Sample-Code&Scripts/Powershell/upload-positions.ps1
- Adapptr/Sample-PostmanCollections/Adapptr.postman_collection
- Adapptr/versions/v2.md
Update the documentation and scripts to remove the X-Client-Environment header
> Deprecate X-Client-Environment

- Sample-XML/Single Equity in a single fund.xml
removed LotSize & MarketCap as they are deprecated
> removed LotSize & MarketCap as they are deprecated

- Adapptr/versions/v2.md
Added information about the v2/composites/usage on Adapptr.
> Added documentation for the ETF Library usage API

- Sample-XML/Option on Sovereign Bond Index Example.xml
Add Example of Option on Sovereign Bond Index
> Add Example of Option on Sovereign Bond Index

- Adapptr/Sample-Code&Scripts/C#/TaskStatus.cs
- Adapptr/Sample-Code&Scripts/C#/UploadPositionsExpost.cs
As per title - adding expost example, and fixing typo in status example
> [skip-sc] Adding expost example, fixing typo

- Adapptr/Sample-ImportFiles/Shareholding Disclosure & Position Limits/Adapptr_upload.csv
Add an example Adapptr CSV file that has columns for both the Shareholding Disclosure product and the Position Limits product.
> :memo: Add example Adapptr SD & PL file

- Adapptr/Sample-ImportFiles/Shareholding Disclosure & Position Limits/Adapptr_upload.csv
The file processed as expected but Github wants all the commas so that it can preview it as a table
> :rotating_light: Correct formatting for Github previews

- Adapptr/Sample-Code&Scripts/Powershell/upload-positions.ps1
Added spaces to make it clearer how to update the body
> update with excludeErrorAssets

- Adapptr/Sample-Code&Scripts/Python/adapptr.py
Adds an example python script for uploading a file to Adapptr endpoint and waiting for a response (successful or failure).
Prints messages to the console for the task id and status report
> :sparkles: Add example Adapptr python script
